
    <div class="ata-music" data-mei="mei/Fuga 3.xml">
      <div class="atalanta-notation-viz atalanta-notation-viz-cmn"></div>
      <div class="atalanta-notation-viz atalanta-notation-viz-audio" 
            data-tempo="45">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="audio/03-P-45bpm-Dry.mp3" data-reverb-mp3="audio/03-P-45bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="audio/03-A-45bpm-Dry.mp3" data-reverb-mp3="audio/03-A-45bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="audio/03-H-45bpm-Dry.mp3" data-reverb-mp3="audio/03-H-45bpm-Reverb.mp3"></div>
      </div>
      <div class="atalanta-notation-viz atalanta-notation-viz-pianoroll"></div>
    </div>