
    <div class="ata-music" data-mei="../data/mei/Fuga 4.xml">
      <div class="ata-viz-cmn"></div>
      <div class="ata-viz-audio" 
            data-tempo="54">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="../assets/audio/04-A-54bpm-Dry.mp3" data-reverb-mp3="../assets/audio/04-A-54bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/04-H-54bpm-Dry.mp3" data-reverb-mp3="../assets/audio/04-H-54bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/04-P-54bpm-Dry.mp3" data-reverb-mp3="../assets/audio/04-P-54bpm-Reverb.mp3"></div>
      </div>
      <div class="ata-viz-pianoroll modal" style="background:#fff"></div>
    </div>