
    <div class="ata-music" data-mei="mei/Fuga 7.xml">
      <div class="atalanta-notation-viz atalanta-notation-viz-cmn"></div>
      <div class="atalanta-notation-viz atalanta-notation-viz-audio" 
            data-tempo="50">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="audio/07-A-50bpm-Dry.mp3" data-reverb-mp3="audio/07-A-50bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="audio/07-H-50bpm-Dry.mp3" data-reverb-mp3="audio/07-H-50bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="audio/07-P-50bpm-Dry.mp3" data-reverb-mp3="audio/07-P-50bpm-Reverb.mp3"></div>
      </div>
      <div class="atalanta-notation-viz atalanta-notation-viz-pianoroll"></div>
    </div>