
    <div class="ata-music" data-mei="../data/mei/Fuga 9.xml">
      <div class="ata-viz-cmn"></div>
      <div class="ata-viz-audio" 
            data-tempo="58">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="../assets/audio/09-A-58bpm-Dry.mp3" data-reverb-mp3="../assets/audio/09-A-58bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/09-H-58bpm-Dry.mp3" data-reverb-mp3="../assets/audio/09-H-58bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/09-P-58bpm-Dry.mp3" data-reverb-mp3="../assets/audio/09-P-58bpm-Reverb.mp3"></div>
      </div>
      <div class="ata-viz-pianoroll"></div>
    </div>