
    <div class="ata-music" data-mei="../data/mei/Fuga 10.xml">
      <div class="ata-viz-cmn"></div>
      <div class="ata-viz-audio" 
            data-tempo="68">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="../assets/audio/10-A-68bpm-Dry.mp3" data-reverb-mp3="../assets/audio/10-A-68bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/10-H-68bpm-Dry.mp3" data-reverb-mp3="../assets/audio/10-H-68bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/10-P-68bpm-Dry.mp3" data-reverb-mp3="../assets/audio/10-P-68bpm-Reverb.mp3"></div>
      </div>
      <div class="ata-viz-pianoroll modal" style="background:#fff"></div>
    </div>