
    <div class="ata-music" data-mei="../data/mei/Fuga 11.xml">
      <div class="ata-viz-cmn"></div>
      <div class="ata-viz-audio" 
            data-tempo="56">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="../assets/audio/11-A-56bpm-Dry.mp3" data-reverb-mp3="../assets/audio/11-A-56bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/11-H-56bpm-Dry.mp3" data-reverb-mp3="../assets/audio/11-H-56bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/11-P-56bpm-Dry.mp3" data-reverb-mp3="../assets/audio/11-P-56bpm-Reverb.mp3"></div>
      </div>
      <!--
      <div class="ata-viz-pianoroll modal"></div>
      -->
    </div>