
    <div class="ata-music" data-mei="../data/mei/Fuga 12.xml">
      <div class="ata-viz-cmn"></div>
      <div class="ata-viz-audio" 
            data-tempo="50">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="../assets/audio/12-A-50bpm-Dry.mp3" data-reverb-mp3="../assets/audio/12-A-50bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/12-H-50bpm-Dry.mp3" data-reverb-mp3="../assets/audio/12-H-50bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/12-P-50bpm-Dry.mp3" data-reverb-mp3="../assets/audio/12-P-50bpm-Reverb.mp3"></div>
      </div>
      <div class="ata-viz-pianoroll"></div>
    </div>