
    <div class="ata-music" data-mei="mei/Fuga 13.xml">
      <div class="ata-viz-cmn"></div>
      <div class="ata-viz-audio" data-tempo="None">
        <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
            data-mp3="audio/13-H-Nonebpm-Dry.mp3" data-reverb-mp3="audio/13-H-Nonebpm-Reverb.mp3"></div>
        <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
            data-mp3="audio/13-A-Nonebpm-Dry.mp3" data-reverb-mp3="audio/13-A-Nonebpm-Reverb.mp3"></div>
        <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
            data-mp3="audio/13-P-Nonebpm-Dry.mp3" data-reverb-mp3="audio/13-P-Nonebpm-Reverb.mp3"></div>
      </div>
      <div class="ata-viz-pianoroll modal"></div>
    </div>