
    <div class="ata-music" data-mei="mei/Fuga 17.xml">
      <div class="atalanta-notation-viz atalanta-notation-viz-cmn"></div>
      <div class="atalanta-notation-viz atalanta-notation-viz-audio" 
            data-tempo="56">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="audio/17-P-56bpm-Dry.mp3" data-reverb-mp3="audio/17-P-56bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="audio/17-A-56bpm-Dry.mp3" data-reverb-mp3="audio/17-A-56bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="audio/17-H-56bpm-Dry.mp3" data-reverb-mp3="audio/17-H-56bpm-Reverb.mp3"></div>
      </div>
      <div class="atalanta-notation-viz atalanta-notation-viz-pianoroll"></div>
    </div>