
    <div class="ata-music" data-mei="../data/mei/Fuga 28.xml">
      <div class="ata-viz-cmn"></div>
      <div class="ata-viz-audio" 
            data-tempo="None">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="../assets/audio/28-A-Nonebpm-Dry.mp3" data-reverb-mp3="../assets/audio/28-A-Nonebpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/28-H-Nonebpm-Dry.mp3" data-reverb-mp3="../assets/audio/28-H-Nonebpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/28-P-Nonebpm-Dry.mp3" data-reverb-mp3="../assets/audio/28-P-Nonebpm-Reverb.mp3"></div>
      </div>
      <div class="ata-viz-pianoroll"></div>
    </div>