
    <div class="ata-music" data-mei="../data/mei/Fuga 46.xml">
      <div class="ata-viz-cmn"></div>
      <div class="ata-viz-audio" 
            data-tempo="52">
            <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
                data-mp3="../assets/audio/46-A-52bpm-Dry.mp3" data-reverb-mp3="../assets/audio/46-A-52bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/46-H-52bpm-Dry.mp3" data-reverb-mp3="../assets/audio/46-H-52bpm-Reverb.mp3"></div>
            <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
                data-mp3="../assets/audio/46-P-52bpm-Dry.mp3" data-reverb-mp3="../assets/audio/46-P-52bpm-Reverb.mp3"></div>
      </div>
      <div class="ata-viz-pianoroll"></div>
    </div>