
    <div class="ata-music" data-mei="mei/Fuga 47.xml">
      <div class="ata-viz-cmn"></div>
      <div class="ata-viz-audio" data-tempo="82">
        <div class="ata-audio-track" data-pan="-.5" data-gain="1" data-reverb-gain="0.6" 
            data-mp3="audio/47-H-82bpm-Dry.mp3" data-reverb-mp3="audio/47-H-82bpm-Reverb.mp3"></div>
        <div class="ata-audio-track" data-pan="0"   data-gain="1" data-reverb-gain="0.6"  
            data-mp3="audio/47-P-82bpm-Dry.mp3" data-reverb-mp3="audio/47-P-82bpm-Reverb.mp3"></div>
        <div class="ata-audio-track" data-pan=".5"  data-gain="1" data-reverb-gain="0.6"  
            data-mp3="audio/47-A-82bpm-Dry.mp3" data-reverb-mp3="audio/47-A-82bpm-Reverb.mp3"></div>
      </div>
      <div class="ata-viz-pianoroll modal"></div>
    </div>