<div class="ata-music" data-mei="../data/mei/excerpts/Fuga 11-e3.xml">
  <div class="ata-viz-cmn"></div>
  <div class="ata-viz-audio" data-tempo="56">
    <div class="ata-audio-track" data-pan="-.5" data-gain="1"
      data-reverb-gain="0.6" data-mp3="../assets/audio/excerpts/11e3-A-56bpm-Dry.mp3"
      data-reverb-mp3="../assets/audio/excerpts/11e3-A-56bpm-Reverb.mp3"></div>
    <div class="ata-audio-track" data-pan="-.5" data-gain="1"
      data-reverb-gain="0.6" data-mp3="../assets/audio/excerpts/11e3-P-56bpm-Dry.mp3"
      data-reverb-mp3="../assets/audio/excerpts/11e3-P-56bpm-Reverb.mp3"></div>
  </div>
  <div class="ata-viz-pianoroll modal" style="background:#fff"></div>
</div>